// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-u_4k_q_EhgfqPUFiENJt_wstDdSKFD8',
    appId: '1:1063328145220:web:b43b06657f8dfaa5b94111',
    messagingSenderId: '1063328145220',
    projectId: 'cicdtest02',
    authDomain: 'cicdtest02.firebaseapp.com',
    storageBucket: 'cicdtest02.appspot.com',
    measurementId: 'G-LDSKV16VK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5X6zlH07-M2DyQSdiykn6EFj4QXP6120',
    appId: '1:1063328145220:android:d37dda96b6f81ce2b94111',
    messagingSenderId: '1063328145220',
    projectId: 'cicdtest02',
    storageBucket: 'cicdtest02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM4nqxf3Xq5TjWIjZ0yrSNuvVQZubFns8',
    appId: '1:1063328145220:ios:973ede13a59d9211b94111',
    messagingSenderId: '1063328145220',
    projectId: 'cicdtest02',
    storageBucket: 'cicdtest02.appspot.com',
    iosClientId: '1063328145220-lkl2jtgsgvuo52on6t6qjr28gkrfc87t.apps.googleusercontent.com',
    iosBundleId: 'com.md.cicdtest02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM4nqxf3Xq5TjWIjZ0yrSNuvVQZubFns8',
    appId: '1:1063328145220:ios:973ede13a59d9211b94111',
    messagingSenderId: '1063328145220',
    projectId: 'cicdtest02',
    storageBucket: 'cicdtest02.appspot.com',
    iosClientId: '1063328145220-lkl2jtgsgvuo52on6t6qjr28gkrfc87t.apps.googleusercontent.com',
    iosBundleId: 'com.md.cicdtest02',
  );
}
